name: demo-crm CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      IMAGE_NAME: demo-crm
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO_NAME: demo-crm-repo
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./demo-crm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          npm run dev &

      - name: Wait for server to start
        run: sleep 5

      - name: Smoke test - check app running
        run: curl http://localhost:3000

      - name: Stop dev server
        run: pkill -f "next dev" || echo "No process found"

      - name: Docker build
        run: docker build -t ${IMAGE_NAME}:latest .

      - name: Docker Compose up
        run: docker compose up -d

      - name: Wait for containers
        run: sleep 5

      - name: Verify containers
        run: docker ps -a

      - name: Docker Compose down
        run: docker compose down -v

      # ✅ GCP auth & image push
      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.SERVICES_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Tag & Push Docker image to Artifact Registry
        env:
          GIT_TAG: v1.0.0
        run: |
          IMAGE_PATH=us-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}
          docker tag ${IMAGE_NAME}:latest ${IMAGE_PATH}:latest
          docker tag ${IMAGE_NAME}:latest ${IMAGE_PATH}:${GIT_TAG}
          docker push ${IMAGE_PATH}:latest
          docker push ${IMAGE_PATH}:${GIT_TAG}

  CD:
    needs: CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./demo-crm
    env:
      IMAGE_NAME: demo-crm
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      REPO_NAME: demo-crm-repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.SERVICES_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Deploy updated image to GKE
        run: |
          gcloud container clusters get-credentials demo-crm-cluster --region ${REGION} --project ${PROJECT_ID}
          IMAGE_URI=us-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:v1.0.0
          kubectl set image deployment/demo-crm-deployment demo-crm-container=${IMAGE_URI}
          kubectl rollout status deployment/demo-crm-deployment
          kubectl get pods
