name: Build and Push to Artifact Registry

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: concrete-fusion-460312-m9

  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/concrete-fusion-460312-m9/demo-crm

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file ./demo-crm/Dockerfile --tag ${{ env.GAR_LOCATION }}
        working-directory: ./demo-crm

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
