name: Build and Push to Artifact Registry

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: concrete-fusion-460312-m9
  REGION: us-central1
  REPOSITORY: demo-crm
  IMAGE_NAME: demo-crm
  IMAGE_TAG: latest
  GAR_HOST: us-central1-docker.pkg.dev
  GAR_PATH: us-central1-docker.pkg.dev/concrete-fusion-460312-m9/demo-crm/demo-crm

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SERVICES_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Verify gcloud CLI
        run: gcloud info

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_HOST }} --quiet

      - name: Build Docker image
        run: |
          docker build . \
            --file ./demo-crm-portfolio/demo-crm/Dockerfile \
            --tag ${{ env.GAR_PATH }}:${{ env.IMAGE_TAG }}
        working-directory: ./demo-crm-portfolio/demo-crm

      - name: Push Docker image
        run: docker push ${{ env.GAR_PATH }}:${{ env.IMAGE_TAG }}
